name: ci-golang
on:
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test ./... -v
      - run: go run main.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id:  docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: thiagodevbrz/ci-cd-github-actions:latests
