name: ci-golang
on:
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-lates
    strategy:
      matrix:
        goVersion: [1.14, 1.15]
    steps:
      - uses: actions/checkout@v2
      - uses: actios/go-setup@v2
        with:
          go-version: ${{ matrix.goVersion }}
      - run: go test ./... -v
      - run: go run main.go
